[package]
name = "wav_f64vec"
version = "0.4.0"
authors = ["Yoshiyuki Koyama <58644862+yoshiyuki-koyama@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
